### ISSUE TITLE
Translate loopback address

### ISSUE THREAD

**Issue by pocke** [pocke/lemonade#6]
If server receives `http://127.0.0.1/hoge`, translate to `http://<client ip addr>/hoge`

TODOs
-------

- [x] Implement
- [x] Optional
- [ ] Update readme => #8

**Comment by pocke** [comment]
I implemented this.
But I want to make this feature optional.

**Comment by pocke** [comment]
Hmm... The CLI instance is not readable by open method.

**Comment by jinmiaoluo** [comment]
This is a good idea. 
I write code on my remote ubuntu server with neovim.

I use lemonade to provide remote clipboard feature for neovim. Also, I make a alias called `xdg-open` for [openBrowser](https://github.com/tyru/open-browser.vim) plugin and [vim-fugitive](https://github.com/tpope/vim-fugitive) so I can quick open a link in ssh terminal on my server ( lemonade client ) . The link will actually open on my local MacBook. 

I hope to use lemonade and [previm](https://github.com/previm/previm) plugin to preview markdown files. `previm` will convert markdown to html into a directory automatically. So I can use lemonade open these html files which stored on my server with `xdg-open /path/to/file.html`. By default,  lemonade client will create a listener on `127.0.0.1:<random-port>/path/to/file.html` and lemonade server will visit  `127.0.0.1:<random-port>/path/to/file.html`. If we can translate loopback address. For example. use domain instead of `127.0.0.1`. My local MacBook will be able to visit these files on my remote server . So `previm` plugin will be able to work ( previm call xdg-open with `xdg-open file:///path/to/file.html`. So it still not right)

I make follow change
```
diff --git a/client/client.go b/client/client.go
index 8b2db7c..3a302c4 100644
--- a/client/client.go
+++ b/client/client.go
@@ -61,7 +61,7 @@ func serveFile(fname string) (string, <-chan struct{}, error) {
                }))
        }()

-       return fmt.Sprintf("http://127.0.0.1:%d/%s", l.Addr().(*net.TCPAddr).Port, fname), finished, nil
+       return fmt.Sprintf("http://jinmiaoluo.cn:%d/%s", l.Addr().(*net.TCPAddr).Port, fname), finished, nil
 }
```
And now I can use `lemonade open file.html` or `xdg-open file.html` on my ubuntu server to call my MacBook to open these files in a browser.

English is not my native language, forgive typing errors.
